export const CLEAR_ARRAY = 'CLEAR_ARRAY'
export const ADD_ITEM = 'ADD_ITEM'
export const ADD_BUN = 'ADD_BUN'
export const DELETE_ITEM = 'DELETE_ITEM'
export const DELETE_BUN = 'DELETE_BUN'
export const SAVE_STATE = 'SAVE_STATE'
