export const GET_FEED_REQUEST: 'GET_FEED_REQUEST' = 'GET_FEED_REQUEST' as const
export const GET_FEED_SUCCESS: 'GET_FEED_SUCCESS' = 'GET_FEED_SUCCESS' as const
export const GET_FEED_FAILED: 'GET_FEED_FAILED' = 'GET_FEED_FAILED' as const

export const WS_CONNECTION_START: 'WS_CONNECTION_START' =
  'WS_CONNECTION_START' as const
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' =
  'WS_CONNECTION_SUCCESS' as const
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' =
  'WS_CONNECTION_ERROR' as const
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' =
  'WS_CONNECTION_CLOSED' as const
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE' as const

export const WS_CONNECTION_AUTH_START: 'WS_CONNECTION_AUTH_START' =
  'WS_CONNECTION_AUTH_START' as const
export const WS_CONNECTION_AUTH_SUCCESS: 'WS_CONNECTION_AUTH_SUCCESS' =
  'WS_CONNECTION_AUTH_SUCCESS' as const
export const WS_CONNECTION_AUTH_ERROR: 'WS_CONNECTION_AUTH_ERROR' =
  'WS_CONNECTION_AUTH_ERROR' as const
export const WS_CONNECTION_AUTH_CLOSED: 'WS_CONNECTION_AUTH_CLOSED' =
  'WS_CONNECTION_AUTH_CLOSED' as const
export const WS_GET_AUTH_MESSAGE: 'WS_GET_AUTH_MESSAGE' =
  'WS_GET_AUTH_MESSAGE' as const

export const GET_AUTH_REQUEST: 'GET_AUTH_REQUEST' = 'GET_AUTH_REQUEST' as const
export const GET_AUTH_SUCCESS: 'GET_AUTH_SUCCESS' = 'GET_AUTH_SUCCESS' as const
export const GET_AUTH_ERROR: 'GET_AUTH_ERROR' = 'GET_AUTH_ERROR' as const
export const GET_AUTH_OUT: 'GET_AUTH_OUT' = 'GET_AUTH_OUT' as const
export const GET_REAUTH: 'GET_REAUTH' = 'GET_REAUTH' as const

export const GET_EMAIL_REQUEST: 'GET_EMAIL_REQUEST' =
  'GET_EMAIL_REQUEST' as const
export const GET_EMAIL_SUCCESS: 'GET_EMAIL_SUCCESS' =
  'GET_EMAIL_SUCCESS' as const
export const GET_EMAIL_ERROR: 'GET_EMAIL_ERROR' = 'GET_EMAIL_ERROR' as const
export const CLEAR_MESSAGE: 'CLEAR_MESSAGE' = 'CLEAR_MESSAGE' as const

export const GET_LOGOUT_REQUEST: 'GET_LOGOUT_REQUEST' =
  'GET_LOGOUT_REQUEST' as const
export const GET_LOGOUT_SUCCESS: 'GET_LOGOUT_SUCCESS' =
  'GET_LOGOUT_SUCCESS' as const
export const GET_LOGOUT_ERROR: 'GET_LOGOUT_ERROR' = 'GET_LOGOUT_ERROR' as const

export const GET_REGISTRATION_REQUEST: 'GET_REGISTRATION_REQUEST' =
  'GET_REGISTRATION_REQUEST' as const
export const GET_REGISTRATION_SUCCESS: 'GET_REGISTRATION_SUCCESS' =
  'GET_REGISTRATION_SUCCESS' as const
export const GET_REGISTRATION_ERROR: 'GET_REGISTRATION_ERROR' =
  'GET_REGISTRATION_ERROR' as const

export const GET_RESETPASS_REQUEST: 'GET_RESETPASS_REQUEST' =
  'GET_RESETPASS_REQUEST' as const
export const GET_RESETPASS_SUCCESS: 'GET_RESETPASS_SUCCESS' =
  'GET_RESETPASS_SUCCESS' as const
export const GET_RESETPASS_ERROR: 'GET_RESETPASS_ERROR' =
  'GET_RESETPASS_ERROR' as const

export const GET_TOKEN_REQUEST: 'GET_TOKEN_REQUEST' =
  'GET_TOKEN_REQUEST' as const
export const GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS' =
  'GET_TOKEN_SUCCESS' as const
export const GET_TOKEN_ERROR: 'GET_TOKEN_ERROR' = 'GET_TOKEN_ERROR' as const

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST' as const
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS' as const
export const GET_USER_ERROR: 'GET_USER_ERROR' = 'GET_USER_ERROR' as const
export const GET_USER_OUT: 'GET_USER_OUT' = 'GET_USER_OUT' as const

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' =
  'GET_ORDER_REQUEST' as const
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' =
  'GET_ORDER_SUCCESS' as const
export const GET_ORDER_ERROR: 'GET_ORDER_ERROR' = 'GET_ORDER_ERROR' as const

export const GET_ORDER_CREATED_REQUEST: 'GET_ORDER_CREATED_REQUEST' =
  'GET_ORDER_CREATED_REQUEST' as const
export const GET_ORDER_CREATED_SUCCESS: 'GET_ORDER_CREATED_SUCCESS' =
  'GET_ORDER_CREATED_SUCCESS' as const
export const GET_ORDER_CREATED_ERROR: 'GET_ORDER_CREATED_ERROR' =
  'GET_ORDER_CREATED_ERROR' as const

export const CLEAR_ARRAY: 'CLEAR_ARRAY' = 'CLEAR_ARRAY' as const
export const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM' as const
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN' as const
export const DELETE_ITEM: 'DELETE_ITEM' = 'DELETE_ITEM' as const
export const DELETE_BUN: 'DELETE_BUN' = 'DELETE_BUN' as const
export const SAVE_STATE: 'SAVE_STATE' = 'SAVE_STATE' as const
